version: "3.7"

services:
  node:
    image:   "node:8-onbuild"
    volumes:
      - ./app:/usr/src/app/
#    ports:
#      - "3000:3000"
    command: "npm start"

  nginx:
    image: "nginx"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    ports:
      - "9000:80"
    depends_on:
      - "node"
